baseURL: "https://shashankkroy.github.io/"
title: S.K.R
paginate: 5
theme: PaperModX

enableRobotsTXT: true
buildDrafts: true
buildFuture: false
buildExpired: false

googleAnalytics: G-M628446BVJ

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # production to enable google analytics, opengraph, twitter-cards and schema.
  title: ExampleSite
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  author: Me
  # author: ["Me", "You"] # multiple authors
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true
  TocSide: 'right'
  math: true

  assets:
    # disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Home"
    icon: /apple-touch-icon.png
    iconHeight: 30

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: Dr. Shashank Kumar Roy
    subtitle: "Researcher, IMT Atlantique, \U0001F1EB\U0001F1F7" 
    imageUrl: "images/IMG_E1175.jpg"
    imageWidth: 250
    imageHeight: 250
    imageTitle: my image
    buttons:
      - name: About me
        url: /about/ 
      - name: CV
        url: /curriculum-vitae/
      - name: Research Statement
        url: /research-statement/

  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my webpage

  socialIcons:
    - name: twitter
      url: "https://twitter.com/_least_action"
    - name: github
      url: "https://github.com/mr-markovian"
    - name: linkedin
      url: "https://www.linkedin.com/in/shashankroy/"
    - name: instagram
      url: "https://instagram.com/dr_roy_sciphy.ai"
    - name: threads
      url: "https://threads.net/dr_roy_sciphy.ai"

  analytics:
    google:
      SiteVerificationTag: "G-M628446BVJ"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/<path_to_repo>/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 60
    - identifier: tags
      name: tags
      url: /tags/
      weight: 50
    - identifier: about me
      name: About Me
      url: /about/
      weight: 10
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 40
    - identifier: research statement
      name: Research Statement
      url: /research statement/
      weight: 20
    - identifier: curriculum vitae
      name: CV
      url: /curriculum vitae/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
